import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { buildRuntimeHtmlV2 } from '../src/runtime/v2';
import { zombieShowcase } from '../src/runtime/v2/zombie-showcase';

void (async () => {
  const html = await buildRuntimeHtmlV2(zombieShowcase);
  const output = path.resolve(process.cwd(), '../app/src/data/last-light-v2.ts');
  writeFileSync(output, `// Generated by server/scripts/build-last-light.ts; edit the runtime fixture, not this file.\nexport const LAST_LIGHT_V2_HTML = ${JSON.stringify(html)};\n`);
  console.log(`Wrote ${output} (${html.length.toLocaleString()} characters).`);
})();
